-- =============================================
-- V3: Fix Password Hash for Dummy Users
-- Password: Test1234!
-- Hash generated by BCryptPasswordEncoder with strength 10
-- =============================================

UPDATE users SET password = '$2a$10$dXJ3SW6G7P50lGmMkkmwe.20cQQubK3.HZWzG3YB1tlRy.fqvM/BG'
WHERE username IN ('seller1', 'seller2', 'seller3', 'buyer1', 'buyer2', 'buyer3');
